name: Deploy DevOps API to AWS

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: devops-test-api
  LAMBDA_FUNCTION_NAME: devops-test-api-function

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Application
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd api
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          cd api
          python -m pytest --version || echo "No tests found - skipping"

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Build and Deploy
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd api
          
          # Build image com tag do commit
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          
          # Push both tags
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Update Lambda function
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Update Lambda with new image
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          # Wait for function to be updated
          aws lambda wait function-updated \
            --function-name $LAMBDA_FUNCTION_NAME

      - name: Run integration tests
        run: |
          # Wait for deployment to propagate
          sleep 30
          
          # Get API URL from terraform output (if available)
          API_URL="https://km7l52whxa.execute-api.us-east-1.amazonaws.com/dev"
          
          # Test endpoints
          echo "Testing /hello endpoint..."
          curl -f $API_URL/hello
          
          echo "Testing /health endpoint..."
          curl -f $API_URL/health
          
          echo "Testing /echo endpoint..."
          curl -f "$API_URL/echo?msg=ci-cd-test"

      - name: Notify deployment success
        if: success()
        run: |
          echo "🚀 Deployment successful!"
          echo "API URL: https://km7l52whxa.execute-api.us-east-1.amazonaws.com/dev"